import * as github from '@actions/github';
import * as core from '@actions/core';
import { Command } from './types';

export class GitHubService {
  private octokit: ReturnType<typeof github.getOctokit>;
  private context: typeof github.context;

  constructor(token: string) {
    this.octokit = github.getOctokit(token);
    this.context = github.context;
  }

  async postComment(issueNumber: number, imageUrls: string[], command: Command): Promise<void> {
    const imageType = command.type === 'concept' ? 'Concept Images' : 'Wireframe Images';
    const MAX_COMMENT_SIZE = 60000; // GitHub limit is 65536, leave some buffer for safety
    
    try {
      const totalImages = imageUrls.length;
      
      // Post each image in a separate comment to avoid size limits
      // Base64 encoded images can be very large, so one image per comment is safest
      for (let i = 0; i < imageUrls.length; i++) {
        let commentBody = '';
        
        // Add header for first image
        if (i === 0) {
          commentBody += `## ${imageType}\n\n`;
          commentBody += `Generated ${totalImages} ${imageType.toLowerCase()} based on the requirements:\n\n`;
        }
        
        // Add image markdown
        commentBody += `### ${imageType.split(' ')[0]} ${i + 1}/${totalImages}\n`;
        commentBody += `![${imageType} ${i + 1}](${imageUrls[i]})\n\n`;
        
        // Add footer for last image
        if (i === imageUrls.length - 1) {
          commentBody += `---\n*Generated by @gen-visual*`;
        } else {
          // Add continuation indicator for intermediate images
          commentBody += `*[${i + 1}/${totalImages} - More images below]*\n`;
        }
        
        // Check if comment size exceeds limit
        if (commentBody.length > MAX_COMMENT_SIZE) {
          core.warning(`Comment ${i + 1} exceeds size limit (${commentBody.length} chars). This may fail.`);
        }
        
        await this.octokit.rest.issues.createComment({
          owner: this.context.repo.owner,
          repo: this.context.repo.repo,
          issue_number: issueNumber,
          body: commentBody.trim()
        });
        
        core.info(`Posted comment ${i + 1}/${totalImages} with image ${i + 1} to issue #${issueNumber}`);
      }
      
      core.info(`Posted ${totalImages} comments with images to issue #${issueNumber}`);
    } catch (error) {
      core.error(`Failed to post comment: ${error}`);
      throw error;
    }
  }

  getIssueContext() {
    const payload = this.context.payload;
    
    return {
      issueNumber: payload.issue?.number || 0,
      issueBody: payload.issue?.body || '',
      commentBody: payload.comment?.body || payload.issue?.body || '',
      repository: `${this.context.repo.owner}/${this.context.repo.repo}`
    };
  }
}
